### ISSUE TITLE
Angular support for 12

### ISSUE THREAD

**Issue by rickvandermey** [Kentico/kontent-angular-http-service#23]
### Motivation

Angular 12 was released in 05-2021. It should support the latest stable as soon as possible, yet only 10 is supported

### Proposed solution

update all angular dependencies, and run tests.

**Comment by Enngage** [comment]
New preview version of this lib now supports Angular 12 with new Javascript delivery SDK (also in preview currently - https://www.npmjs.com/package/@kentico/kontent-delivery/v/11.0.0-2)
